import { z } from 'zod';

export const teamSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  siret: z.string().nullable(),
  address: z.string().nullable(),
  phone: z.string().nullable(),
  email: z.string().nullable(),
  mobile: z.string().nullable(),
  website: z.string().nullable(),
  logo_url: z.string().nullable(),
  tva_number: z.string().nullable(),
  tva_exempt: z.boolean(),
  ape_code: z.string().nullable(),
  legal_form: z.string().nullable(),
  capital_social: z.number().int().nullable(),
  rcs_city: z.string().nullable(),
  rm_city: z.string().nullable(),
  activity_description: z.string().nullable(),
  insurance_company: z.string().nullable(),
  insurance_policy_number: z.string().nullable(),
  insurance_coverage_zone: z.string().nullable(),
  payment_terms: z.string().nullable(),
  deposit_percent: z.number().int().nullable(),
  early_payment_discount: z.string().nullable(),
  late_penalty_rate: z.string().nullable(),
  recovery_fee: z.number().int().nullable(),
  custom_clauses: z.array(z.string()),
  original_document_url: z.string().nullable(),
  terms_accepted_at: z.date().nullable(),
  stripe_customer_id: z.string().nullable(),
  trial_ends_at: z.date().nullable(),
  subscription_status: z.enum(['trial', 'active', 'cancelled', 'expired']),
  created_at: z.date(),
});

export type TeamRow = z.infer<typeof teamSchema>;
